# Generated by Django 4.2.1 on 2023-05-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='detime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='petime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='pstime',
            field=models.TimeField(blank=True),
        ),
    ]
